output: basic
random_state: 4242

features:
 more_jaccard: -1
 spacy: -1
 distance: -1
 tfidf: reduce
 intersect: -1
 alphabet: -1
 number: -1
 tfidf_score: -1

models:
 xgb: {'max_depth':6,'n_estimators':1500,'learning_rate':0.06,'subsample':0.8,'colsample_bytree':0.8,'colsample_bylevel':1,'reg_alpha':0.5,'reg_lambda':0,'seed':4213,'silent':1,'objective':'binary:logistic','nthread':8}
 lr: {'max_iter':200, 'penalty':'l2', 'C': 0.1, 'random_state': 4242, 'n_jobs':-1}
